apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jmeter
  name: podname
  namespace: default
spec:
  containers:
  - image: imagename
    name: jmeter
    command: ["sh","-c","jmeter -n -H=172.16.102.152 -P=8080 -t 1.jmx -l data.csv -q test.properties"]
  restartPolicy: Never
status: {}
